### ISSUE TITLE
umm

### ISSUE THREAD

**Issue by DragonEggFish** [Explosion-Scratch/blog#1]
why do you need a blog
and where will you host the site

**Comment by Explosion-Scratch** [comment]
Hosted on GitHub pages https://explosion-scratch.github.io/blog

**Comment by Explosion-Scratch** [comment]
But currently it shows a blank page, still working on fixing that
![](https://media1.giphy.com/media/YrBRYRDN4M5ryrNOND/giphy.gif)

Thanks for checking out the project btw!

**Comment by Explosion-Scratch** [comment]
I'm gonna close this, tell me if you have any more questions! Btw blog is up now! Deployment to GitHub pages works!

**Comment by mmRoshani** [comment]
Hi, I was writing my own GitHub page in vue.js and then accidentally saw your awesome project on https://vuejsexamples.com/tag/blog/ so first of all thank you for your perfect work.

My question is how to deploy this project on my own ???.github.io page?
I changed the URLs in nuxt.config.js but didn't work.
Are there any other things that I should do before deployment?

Thanks for your consideration.

**Comment by Explosion-Scratch** [comment]
> Hi, I was writing my own GitHub page in vue.js and then accidentally saw your awesome project on https://vuejsexamples.com/tag/blog/ so first of all thank you for your perfect work.
> 
> My question is how to deploy this project on my own ???.github.io page? I changed the URLs in nuxt.config.js but didn't work. Are there any other things that I should do before deployment?
> 
> Thanks for your consideration.

See the issue response
