### ISSUE TITLE
Question regarding your blog

### ISSUE THREAD

**Issue by Chiroyce1** [Explosion-Scratch/blog#2]
@Explosion-Scratch 

I was currently searching for a browser based password encryption/decryption system and I came across [your blog](https://explosion-scratch.github.io/blog/cryptography-basics/#part-2-the-web-crypto-api), which provided some very nice functions that I could use. I was successfully able to use them, but I have a few questions

1. Do I need to credit you? If yes, in what way?
2. How do I check if decryption fails? I am currently using this
```js
    let decrypted;
    try {
        decrypted = await decrypt(demoString, password);
    } catch (error) {
        console.error("Incorrect Password!");
        return;
    }
```
And I'm not sure if there is an easier way...

**Comment by Chiroyce1** [comment]
Also if I try to encrypt a file which is around ~400KB, it says `Error - RangeError: too many arguments provided for a function call`

**Comment by Explosion-Scratch** [comment]
> Also if I try to encrypt a file which is around ~400KB, it says `Error - RangeError: too many arguments provided for a function call`

Make sure the file is a string, you can use the FileReader API for this (DataURL, etc)

**Comment by Explosion-Scratch** [comment]
> @Explosion-Scratch
> 
> I was currently searching for a browser based password encryption/decryption system and I came across [your blog](https://explosion-scratch.github.io/blog/cryptography-basics/#part-2-the-web-crypto-api), which provided some very nice functions that I could use. I was successfully able to use them, but I have a few questions
> 
> 1. Do I need to credit you? If yes, in what way?
Not _need to_ but it'd be nice, a simple comment like this would be just fine:
```js
// Credit to @Explosion-Scratch on GH for this function
```

> 2. How do I check if decryption fails? I am currently using this
```js
let demoString = Math.random().toString(36).slice(2).repeat(~~(Math.random() * 20));
let pw = Math.random().toString(36).slice(2);
(async () => {
  console.assert(demoString === await decrypt(await encrypt(demoString, pw), pw));
})();

**Comment by Chiroyce1** [comment]
> > Also if I try to encrypt a file which is around ~400KB, it says `Error - RangeError: too many arguments provided for a function call`
> 
> Make sure the file is a string, you can use the FileReader API for this (DataURL, etc)

Yes, that's what I'm using. I'm using the FileReader API to convert the file into base64, but when it tries to encrypt it I get the same error. And I did make sure that the base64 is a string
<img width="214" alt="image" src="https://user-images.githubusercontent.com/97374054/166438259-ec6f2abf-b99f-40d3-b46b-b92018051685.png">

This is my code
```js
const fileToBase64 = (file) => {
    return new Promise((resolve, reject) => {
        // This is just a way to neatly catch errors
        // and also convert the file to base64
        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = () => resolve(reader.result)
        reader.onerror = error => reject(error)
    })
}

async function main() {
    let base64 = await fileToBase64(file);
    const encrypted = await encrypt(base64, password);
    // `encrypted` is ""
}

**Comment by Chiroyce1** [comment]
@Explosion-Scratch ^

**Comment by Explosion-Scratch** [comment]
Oh yeah, could you make a codepen for it or something?

**Comment by Chiroyce1** [comment]
Uh, replit? https://cryptotest.chiroyce.repl.co/ (encrypting any file >500KB produces a blank output and logs error to console.log)

source code - https://replit.com/@Chiroyce/cryptotest

**Comment by Chiroyce1** [comment]
@Explosion-Scratch (I'm pinging you because I think you aren't subscribed to this thread or watching this repo)

**Comment by Explosion-Scratch** [comment]
> @Explosion-Scratch (I'm pinging you because I think you aren't subscribed to this thread or watching this repo)

Nope, I'm subscribed to the thread and watching the repo

**Comment by Chiroyce1** [comment]
Ok.. have you found the cause of the error yet? Sorry if I'm bothering you with this doubt..

**Comment by Explosion-Scratch** [comment]
I'm getting this error: 
```
Error - RangeError: Maximum call stack size exceeded (crypto.js:58)
```

**Comment by Explosion-Scratch** [comment]
Working on debugging rn

**Comment by Explosion-Scratch** [comment]
It's because of the way I convert base64 to and from buffers

**Comment by Explosion-Scratch** [comment]
Alright, this works: https://codepen.io/explosion-scratch/full/abqvNwQ

**Comment by Explosion-Scratch** [comment]
Also, your encryption method is incredibly inefficient, it would probably be best to convert the file to an ArrayBuffer then convert that directly (remove the line that converts the buffer to base64), because currently the flow from file to encrypted is like this:
```mermaid
flowchart TD
    file[File selected] --> b64
    b64[File converted to a base 64 string] --> E
    subgraph E[Encryption function]
        direction TB
        a[String converted to base64 buffer to encrypt] --> b[Buffer encrypted] --> c[Resultant encrypted buffer converted to string]
    end
```

**Comment by Chiroyce1** [comment]
Thanks a lot!! It works now! 😀
