### ISSUE TITLE
Instruction to deploy on our own github page

### ISSUE THREAD

**Issue by mmRoshani** [Explosion-Scratch/blog#3]
Hi, I was writing my own GitHub page in `vue.js` and then accidentally saw your awesome project on `https://vuejsexamples.com/tag/blog/` so first of all thank you for your perfect work.

My question is how to deploy this project on my own `???.github.io` page?
I changed the URLs in `nuxt.config.js` but didn't work.
Are there any other things that I should do before deployment?

Thanks for your consideration.

**Comment by mmRoshani** [comment]
Oops, i shouldn't ask this here

**Comment by Explosion-Scratch** [comment]
No problem, change the URL in nuxt.config.js and then make the repo build to a github pages branch (this can be titled anything). Every push should trigger a github action that generates the HTML and CSS for your website. Then go into settings > pages (on the repo) and select the branch and save.

<img width="890" alt="image" src="https://user-images.githubusercontent.com/61319150/176981405-3f6ed842-de09-4373-bc9c-9686b9803489.png">


You can use this file as a github workflow if you just want something easy:

https://github.com/Explosion-Scratch/blog/blob/2a1029c1c31215a53bd333f9d4fe95bd58afd589/.github/workflows/deploy.yml

**Comment by mmRoshani** [comment]
thanks for your consideration.

**Comment by Explosion-Scratch** [comment]
Also please update your [duplicate website](https://github.com/mmRoshani/mmRoshani.github.io) to include attribution to me.
